[package]
name = "fasta_cli_toolkit"
version = "1.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = {version = "0.3"}
rand = "0.8.4"
textwrap = "0.15"

