[package]
name = "fasta_cli_toolkit"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = {version = "0.3"}
rand = "0.8.4"
textwrap = "0.15"
hwloc = "0.3.0"

[profile.release]
lto = true
